### ISSUE TITLE
Export feature doesn't work.

### ISSUE THREAD

**Issue by vainwashere** [Wavesonics/hammer-editor#35]
For more info,
I'm using a Realme C30, Android Version 11.

Upon taping export, the app prompts me to choose the export location. But when I do so, the app restarts and nothing happens. If it try to export again, I get prompted again to choose export location. Upon repeating this process multiple times, my device sends a warning that the app has crashed multiple times.

I haven't tried replicating this issue on my other phone yet, so not sure if it's just a me problem.

**Comment by robonxt** [comment]
Same problem here. Running 1.2.2 from fdroid (IzzyOnDroid repo). OnePlus 8T+ OxygenOS 13 (Android 13)

**Comment by Wjxfi** [comment]
Same

```
FATAL EXCEPTION: DefaultDispatcher-worker-4
Process: com.darkrockstudios.apps.hammer.android, PID: 29432
java.io.FileNotFoundException: content:/com.android.externalstorage.documents/tree/primary%3AHammer/Alice In Wonderland.md: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:174)
	at okio.Okio.sink(Unknown Source:1)
	at okio.Okio__JvmOkioKt.sink$default(JvmOkio.kt:174)
	at okio.Okio.sink$default(Unknown Source:1)
	at okio.JvmSystemFileSystem.sink(JvmSystemFileSystem.kt:101)
	at com.darkrockstudios.apps.hammer.common.data.projecteditorrepository.ProjectEditorRepositoryOkio.exportStory(ProjectEditorRepositoryOkio.kt:982)
	at com.darkrockstudios.apps.hammer.common.components.projecthome.ProjectHomeComponent.exportProject(ProjectHomeComponent.kt:74)
	at com.darkrockstudios.apps.hammer.common.projecthome.ProjectHomeUiKt$Actions$3$1.invokeSuspend(ProjectHomeUi.kt:371)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@9e1da8c, androidx.compose.runtime.BroadcastFrameClock@a08e5d5, StandaloneCoroutine{Cancelling}@38ef1ea, Dispatchers.Default]
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8136)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 15 more
```

**Comment by Wavesonics** [comment]
This is fixed in `develop` now and will ship with the next release.
