### ISSUE TITLE
[Bug] Wrong Global Settings path?

### ISSUE THREAD

**Issue by robonxt** [Wavesonics/hammer-editor#40]
As requested by @Wavesonics in discord, here is the full logs in the terminal when trying to run the hammer application.

```Microsoft Windows [Version 10.0.22621.2134]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>"C:\Program Files\hammer\hammer.exe"
Aug 14, 2023 9:45:44 PM io.github.aakira.napier.DebugAntilog performLog
INFO: [INFO] Koin - loaded 45 definitions in 7.0218 ms
Aug 14, 2023 9:45:44 PM io.github.aakira.napier.DebugAntilog performLog
SEVERE: [ERROR] Koin - * Instance creation error : could not create instance for '[Singleton:'com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository',binds:com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository]': java.nio.file.InvalidPathException: Illegal charobonxt\HammerProjects\server.json
        java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        java.base/java.nio.file.Path.of(Unknown Source)
        java.base/java.nio.file.Paths.get(Unknown Source)
        okio.Path.toNioPath(Path.kt:103)
        okio.NioSystemFileSystem.metadataOrNull(NioSystemFileSystem.kt:37)
        okio.internal._FileSystemKt.commonExists(-FileSystem.kt:38)
        okio.FileSystem.exists(FileSystem.kt:38)
        com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository.loadServerSettings(GlobalSettingsRepository.kt:128)
        com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository.<init>(GlobalSettingsRepository.kt:61)
        com.darkrockstudios.apps.hammer.common.dependencyinjection.MainModuleKt$mainModule$1$invoke$$inlined$singleOf$default$5.invoke(SingleOf.kt:229)
        com.darkrockstudios.apps.hammer.common.dependencyinjection.MainModuleKt$mainModule$1$invoke$$inlined$singleOf$default$5.invoke(SingleOf.kt:69)
        org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
        org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
        org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
        org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
        org.koin.core.scope.Scope.get(Scope.kt:210)
        com.darkrockstudios.apps.hammer.desktop.MainKt.main(Main.kt:170)
Exception in thread "main" org.koin.core.error.InstanceCreationException: Could not create instance for '[Singleton:'com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository',binds:com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository]'
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:58)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
        at org.koin.core.scope.Scope.get(Scope.kt:210)
        at com.darkrockstudios.apps.hammer.desktop.MainKt.main(Main.kt:170)
obonxt\HammerProjects\server.jsonathException: Illegal char <
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at okio.Path.toNioPath(Path.kt:103)
        at okio.NioSystemFileSystem.metadataOrNull(NioSystemFileSystem.kt:37)
        at okio.internal._FileSystemKt.commonExists(-FileSystem.kt:38)
        at okio.FileSystem.exists(FileSystem.kt:38)
        at com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository.loadServerSettings(GlobalSettingsRepository.kt:128)
        at com.darkrockstudios.apps.hammer.common.data.globalsettings.GlobalSettingsRepository.<init>(GlobalSettingsRepository.kt:61)
        at com.darkrockstudios.apps.hammer.common.dependencyinjection.MainModuleKt$mainModule$1$invoke$$inlined$singleOf$default$5.invoke(SingleOf.kt:229)
        at com.darkrockstudios.apps.hammer.common.dependencyinjection.MainModuleKt$mainModule$1$invoke$$inlined$singleOf$default$5.invoke(SingleOf.kt:69)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
        ... 10 more
Failed to launch JVM

C:\Windows\System32>```

**Comment by Wavesonics** [comment]
This looks to be a bug in the TOML parser library: https://github.com/akuleshov7/ktoml/issues/225

The workaround for now, if you run into this, is to go into your `global_settings.json` file, and add in any missing escape slashes in the project directory field:
`projectsDirectory = "C:\\Users\\USERNAME\\HammerProjects"`

**Comment by Wavesonics** [comment]
@robonxt I may have a fix for this. It'll be in the next release.
